
# This file is automatically generated, you probably don't want to edit this

sampleSizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sampleSizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            tipo = "media",
            e_OM = 1,
            S = 1,
            level_OM = 0.95,
            e_OP = 0.05,
            P = 0.5,
            level_OP = 0.95,
            pow_IP = 0.85,
            level_IP = 0.95,
            dif_IP = 0.05,
            P1 = 0.5,
            P2 = 0.6,
            level_IM = 0.95,
            pow_IM = 0.85,
            dif_IM = 1,
            S1 = 1,
            S2 = 1,
            level_PM = 0.95,
            pow_PM = 0.85,
            dif_PM = 1,
            SC = 1, ...) {

            super$initialize(
                package="sampleSize",
                name="sampleSize",
                requiresData=FALSE,
                ...)

            private$..tipo <- jmvcore::OptionList$new(
                "tipo",
                tipo,
                options=list(
                    "media",
                    "proporcion",
                    "dosMediasVD",
                    "dosMediasVC",
                    "dosProporciones"),
                default="media")
            private$..e_OM <- jmvcore::OptionNumber$new(
                "e_OM",
                e_OM,
                default=1)
            private$..S <- jmvcore::OptionNumber$new(
                "S",
                S,
                default=1)
            private$..level_OM <- jmvcore::OptionNumber$new(
                "level_OM",
                level_OM,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..e_OP <- jmvcore::OptionNumber$new(
                "e_OP",
                e_OP,
                default=0.05,
                min=0.0001,
                max=0.9999)
            private$..P <- jmvcore::OptionNumber$new(
                "P",
                P,
                default=0.5,
                min=0.0001,
                max=1)
            private$..level_OP <- jmvcore::OptionNumber$new(
                "level_OP",
                level_OP,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..pow_IP <- jmvcore::OptionNumber$new(
                "pow_IP",
                pow_IP,
                default=0.85,
                min=0.0001,
                max=1)
            private$..level_IP <- jmvcore::OptionNumber$new(
                "level_IP",
                level_IP,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..dif_IP <- jmvcore::OptionNumber$new(
                "dif_IP",
                dif_IP,
                default=0.05,
                min=0.0001,
                max=0.9999)
            private$..P1 <- jmvcore::OptionNumber$new(
                "P1",
                P1,
                default=0.5,
                min=0.0001,
                max=1)
            private$..P2 <- jmvcore::OptionNumber$new(
                "P2",
                P2,
                default=0.6,
                min=0.0001,
                max=1)
            private$..level_IM <- jmvcore::OptionNumber$new(
                "level_IM",
                level_IM,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..pow_IM <- jmvcore::OptionNumber$new(
                "pow_IM",
                pow_IM,
                default=0.85,
                min=0.0001,
                max=0.9999)
            private$..dif_IM <- jmvcore::OptionNumber$new(
                "dif_IM",
                dif_IM,
                default=1)
            private$..S1 <- jmvcore::OptionNumber$new(
                "S1",
                S1,
                default=1)
            private$..S2 <- jmvcore::OptionNumber$new(
                "S2",
                S2,
                default=1)
            private$..level_PM <- jmvcore::OptionNumber$new(
                "level_PM",
                level_PM,
                default=0.95,
                min=0.0001,
                max=0.9999)
            private$..pow_PM <- jmvcore::OptionNumber$new(
                "pow_PM",
                pow_PM,
                default=0.85,
                min=0.0001,
                max=0.9999)
            private$..dif_PM <- jmvcore::OptionNumber$new(
                "dif_PM",
                dif_PM,
                default=1)
            private$..SC <- jmvcore::OptionNumber$new(
                "SC",
                SC,
                default=1)

            self$.addOption(private$..tipo)
            self$.addOption(private$..e_OM)
            self$.addOption(private$..S)
            self$.addOption(private$..level_OM)
            self$.addOption(private$..e_OP)
            self$.addOption(private$..P)
            self$.addOption(private$..level_OP)
            self$.addOption(private$..pow_IP)
            self$.addOption(private$..level_IP)
            self$.addOption(private$..dif_IP)
            self$.addOption(private$..P1)
            self$.addOption(private$..P2)
            self$.addOption(private$..level_IM)
            self$.addOption(private$..pow_IM)
            self$.addOption(private$..dif_IM)
            self$.addOption(private$..S1)
            self$.addOption(private$..S2)
            self$.addOption(private$..level_PM)
            self$.addOption(private$..pow_PM)
            self$.addOption(private$..dif_PM)
            self$.addOption(private$..SC)
        }),
    active = list(
        tipo = function() private$..tipo$value,
        e_OM = function() private$..e_OM$value,
        S = function() private$..S$value,
        level_OM = function() private$..level_OM$value,
        e_OP = function() private$..e_OP$value,
        P = function() private$..P$value,
        level_OP = function() private$..level_OP$value,
        pow_IP = function() private$..pow_IP$value,
        level_IP = function() private$..level_IP$value,
        dif_IP = function() private$..dif_IP$value,
        P1 = function() private$..P1$value,
        P2 = function() private$..P2$value,
        level_IM = function() private$..level_IM$value,
        pow_IM = function() private$..pow_IM$value,
        dif_IM = function() private$..dif_IM$value,
        S1 = function() private$..S1$value,
        S2 = function() private$..S2$value,
        level_PM = function() private$..level_PM$value,
        pow_PM = function() private$..pow_PM$value,
        dif_PM = function() private$..dif_PM$value,
        SC = function() private$..SC$value),
    private = list(
        ..tipo = NA,
        ..e_OM = NA,
        ..S = NA,
        ..level_OM = NA,
        ..e_OP = NA,
        ..P = NA,
        ..level_OP = NA,
        ..pow_IP = NA,
        ..level_IP = NA,
        ..dif_IP = NA,
        ..P1 = NA,
        ..P2 = NA,
        ..level_IM = NA,
        ..pow_IM = NA,
        ..dif_IM = NA,
        ..S1 = NA,
        ..S2 = NA,
        ..level_PM = NA,
        ..pow_PM = NA,
        ..dif_PM = NA,
        ..SC = NA)
)

sampleSizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sampleSizeResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size Results")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Resultado"))}))

sampleSizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "sampleSizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "sampleSize",
                name = "sampleSize",
                version = c(1,0,0),
                options = options,
                results = sampleSizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Sample Size Calculator
#'
#' 
#' @param tipo .
#' @param e_OM .
#' @param S .
#' @param level_OM .
#' @param e_OP .
#' @param P .
#' @param level_OP .
#' @param pow_IP .
#' @param level_IP .
#' @param dif_IP .
#' @param P1 .
#' @param P2 .
#' @param level_IM .
#' @param pow_IM .
#' @param dif_IM .
#' @param S1 .
#' @param S2 .
#' @param level_PM .
#' @param pow_PM .
#' @param dif_PM .
#' @param SC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
sampleSize <- function(
    tipo = "media",
    e_OM = 1,
    S = 1,
    level_OM = 0.95,
    e_OP = 0.05,
    P = 0.5,
    level_OP = 0.95,
    pow_IP = 0.85,
    level_IP = 0.95,
    dif_IP = 0.05,
    P1 = 0.5,
    P2 = 0.6,
    level_IM = 0.95,
    pow_IM = 0.85,
    dif_IM = 1,
    S1 = 1,
    S2 = 1,
    level_PM = 0.95,
    pow_PM = 0.85,
    dif_PM = 1,
    SC = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("sampleSize requires jmvcore to be installed (restart may be required)")


    options <- sampleSizeOptions$new(
        tipo = tipo,
        e_OM = e_OM,
        S = S,
        level_OM = level_OM,
        e_OP = e_OP,
        P = P,
        level_OP = level_OP,
        pow_IP = pow_IP,
        level_IP = level_IP,
        dif_IP = dif_IP,
        P1 = P1,
        P2 = P2,
        level_IM = level_IM,
        pow_IM = pow_IM,
        dif_IM = dif_IM,
        S1 = S1,
        S2 = S2,
        level_PM = level_PM,
        pow_PM = pow_PM,
        dif_PM = dif_PM,
        SC = SC)

    analysis <- sampleSizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

